###
POST https://login-register-api-sez8.onrender.com/register/
Content-Type: application/json

{    
    "username": "abcdef",
    "name":"saipavan",
    "password": "rahul@456",
    "gender":"male",
    "location":"hyderabad"
}
###

POST https://login-register-api-sez8.onrender.com/login/
Content-Type: application/json

{
    "username": "abcdef",
    "password": "rahul@456"
}